soap-hil: add scorch demo and options to run without hardware
sandialabs/sceptre-phenix-topologies pull request #9
Opened 2024-11-06 14:31 UTC by cmulk

2024-11-07 21:06 UTC, GhostofGoes requested changes
LGTM. Just a few minor spelling and format issues I found while reading through it.

2024-11-07 21:06 UTC, GhostofGoes commented on soap-hil/README.md
> +In addition to the topology, this repo includes a demo attack against the PLC to manipulate and destablize the power system model. In addition, a SCORCH pipeline is included in the scenario which can
`captur` -> `capture`

2024-11-07 21:06 UTC, GhostofGoes commented on soap-hil/README.md
> +* Start by finding the applicable exploit `search ignition`
Indentation needed

2024-11-07 21:06 UTC, GhostofGoes commented on soap-hil/README.md
> +5. At this point the pipeline should complete and you can go back to `Files` tab of the main experiment page do view and download artifacts from the Scorch run:
`do view` -> `to view`

2024-11-18 14:10 UTC, cmulk commented on soap-hil/README.md
> +In addition to the topology, this repo includes a demo attack against the PLC to manipulate and destablize the power system model. In addition, a SCORCH pipeline is included in the scenario which can
done

2024-11-18 14:13 UTC, cmulk commented on soap-hil/README.md
> +* Start by finding the applicable exploit `search ignition`
done

2024-11-18 14:13 UTC, cmulk commented on soap-hil/README.md
> +5. At this point the pipeline should complete and you can go back to `Files` tab of the main experiment page do view and download artifacts from the Scorch run:
done

2024-11-18 23:01 UTC, GhostofGoes approved these changes

2024-11-18 23:02 UTC, GhostofGoes commented
@cmulk LGTM, good to merge if you're ready.

2024-12-09 19:51 UTC, merged